site_name: ISXOgre Documentation
site_url: https://kannkor.github.io/ISXOgre/
repo_url: https://github.com/Kannkor/ISXOgre
repo_name: Kannkor/ISXOgre

theme:
  name: material
  palette:
    - scheme: slate
      primary: deep orange
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: deep orange
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

nav:
  - Home: index.md
  - EQ2:
    - EQ2/index.md
    - Getting Started:
      - Why OgreBot?: EQ2/getting-started/why-ogrebot.md
      - Installation: EQ2/getting-started/installation.md
      - Auto-Loading ISXOgre: EQ2/getting-started/auto-loading.md
      - First Run: EQ2/getting-started/first-run.md
      - FAQ: EQ2/getting-started/faq.md
      - Connecting Computers: EQ2/getting-started/connect-computers.md
      - Copy from Console: EQ2/getting-started/copy-from-console.md
      - Remove FPS Display: EQ2/getting-started/remove-fps-display.md
      - Bot Stops Casting: EQ2/getting-started/bot-stops-casting.md
      - Repatching: EQ2/getting-started/repatching.md
    - OgreBot:
      - EQ2/ogrebot/index.md
      - Tabs:
        - EQ2/ogrebot/tabs/index.md
        - Settings: EQ2/ogrebot/tabs/settings.md
        - Setup: EQ2/ogrebot/tabs/setup.md
        - Settings 2: EQ2/ogrebot/tabs/settings2.md
        - Assist: EQ2/ogrebot/tabs/assist.md
        - Loot: EQ2/ogrebot/tabs/loot.md
        - Cast Stack: EQ2/ogrebot/tabs/cast-stack.md
        - Pre-Cast: EQ2/ogrebot/tabs/pre-cast.md
        - Post-Cast: EQ2/ogrebot/tabs/post-cast.md
        - Crowd Control: EQ2/ogrebot/tabs/crowd-control.md
        - Items: EQ2/ogrebot/tabs/items.md
        - Auto Target: EQ2/ogrebot/tabs/auto-target.md
        - Announce: EQ2/ogrebot/tabs/announce.md
        - OSA: EQ2/ogrebot/tabs/osa.md
        - Other: EQ2/ogrebot/tabs/other.md
        - Relay Groups: EQ2/ogrebot/tabs/relay-groups.md
        - Load: EQ2/ogrebot/tabs/load.md
        - Unload: EQ2/ogrebot/tabs/unload.md
        - Equipment Info: EQ2/ogrebot/tabs/equipment-info.md
        - Chat Events: EQ2/ogrebot/tabs/chat-events.md
        - On Zone: EQ2/ogrebot/tabs/on-zone.md
        - Spawn Events: EQ2/ogrebot/tabs/spawn-events.md
        - Despawn Events: EQ2/ogrebot/tabs/despawn-events.md
        - HUDs: EQ2/ogrebot/tabs/huds.md
        - Ascension: EQ2/ogrebot/tabs/ascension.md
        - Ability Embargo: EQ2/ogrebot/tabs/ability-embargo.md
        - OgreConsole: EQ2/ogrebot/tabs/ogre-console.md
        - Uplink Info: EQ2/ogrebot/tabs/uplink-info.md
        - Key Binds: EQ2/ogrebot/tabs/key-binds.md
        - EQ2 Chars: EQ2/ogrebot/tabs/eq2-chars.md
        - Debug: EQ2/ogrebot/tabs/debug.md
        - Admin: EQ2/ogrebot/tabs/admin.md
      - Aliases: EQ2/ogrebot/aliases.md
      - Profiles: EQ2/ogrebot/profiles.md
      - Instance Controller: EQ2/ogrebot/instance-controller.md
    - Tools:
      - OgreCraft: EQ2/tools/ogrecraft.md
      - Harvesting: EQ2/tools/harvesting.md
      - Inventory Manager: EQ2/tools/inventory-manager.md
      - Collection Manager: EQ2/tools/collection-manager.md
      - Auto Login: EQ2/tools/auto-login.md
      - OgreMapper: EQ2/tools/ogre-mapper.md
    - Encounter Coding:
      - EQ2/encounter-coding/index.md
      - Rage of Cthurath:
        - Gerion - Ark of Ascension [Untold Heroic]: EQ2/encounter-coding/_Exp_22_Rage_of_Cthurath/gerion-ark-of-ascension-untold-heroic.md
        - Gerion - Captive Audience [Raid]: EQ2/encounter-coding/_Exp_22_Rage_of_Cthurath/gerion-captive-audience-raid.md
        - Gerion - Dominion of Pain [Untold Heroic]: EQ2/encounter-coding/_Exp_22_Rage_of_Cthurath/gerion-dominion-of-pain-untold-heroic.md
        - The Unknown - Edge of Oblivion [Untold Heroic]: EQ2/encounter-coding/_Exp_22_Rage_of_Cthurath/the-unknown-edge-of-oblivion-untold-heroic.md
        - The Unknown - Sacrificial Pursuits [Untold Heroic]: EQ2/encounter-coding/_Exp_22_Rage_of_Cthurath/the-unknown-sacrificial-pursuits-untold-heroic.md
        - Yon Gorroth - The Infinite Abyss [Raid]: EQ2/encounter-coding/_Exp_22_Rage_of_Cthurath/yon-gorroth-the-infinite-abyss-raid.md
        - Yon Gorroth - Voidshell Caverns [Raid]: EQ2/encounter-coding/_Exp_22_Rage_of_Cthurath/yon-gorroth-voidshell-caverns-raid.md
        - Zon Zobboz - Gaze of the Oglth [Raid]: EQ2/encounter-coding/_Exp_22_Rage_of_Cthurath/zon-zobboz-gaze-of-the-oglth-raid.md
        - Zon Zobboz - The Chimeric Chain [Untold Heroic]: EQ2/encounter-coding/_Exp_22_Rage_of_Cthurath/zon-zobboz-the-chimeric-chain-untold-heroic.md
        - Zon Zobboz - The Graftwerk [Untold Heroic]: EQ2/encounter-coding/_Exp_22_Rage_of_Cthurath/zon-zobboz-the-graftwerk-untold-heroic.md
        - Zon Zobboz - The Outer Swarmyard [Raid]: EQ2/encounter-coding/_Exp_22_Rage_of_Cthurath/zon-zobboz-the-outer-swarmyard-raid.md
      - Scars of Destruction:
        - Blackhook Spiral - Corrupted Caldera [Heroic II]: EQ2/encounter-coding/_Exp_21_Scars_of_Destruction/blackhook-spiral-corrupted-caldera-heroic-ii.md
        - Blackhook Spiral - Fort Sunder [Heroic II]: EQ2/encounter-coding/_Exp_21_Scars_of_Destruction/blackhook-spiral-fort-sunder-heroic-ii.md
        - Blackhook Spiral - Frenzied Breach [Raid]: EQ2/encounter-coding/_Exp_21_Scars_of_Destruction/blackhook-spiral-frenzied-breach-raid.md
        - Blackhook Spiral - Spiritual Terror [Raid]: EQ2/encounter-coding/_Exp_21_Scars_of_Destruction/blackhook-spiral-spiritual-terror-raid.md
        - Dragon Necropolis - Ancient Tombs [Raid]: EQ2/encounter-coding/_Exp_21_Scars_of_Destruction/dragon-necropolis-ancient-tombs-raid.md
        - Dragon Necropolis - Chetari Warrens [Heroic II]: EQ2/encounter-coding/_Exp_21_Scars_of_Destruction/dragon-necropolis-chetari-warrens-heroic-ii.md
        - Dragon Necropolis - Disturbed Vaults [Raid]: EQ2/encounter-coding/_Exp_21_Scars_of_Destruction/dragon-necropolis-disturbed-vaults-raid.md
        - Flooded Scar - Abyssal Assault [Raid]: EQ2/encounter-coding/_Exp_21_Scars_of_Destruction/flooded-scar-abyssal-assault-raid.md
        - Kael Drakkel - Abdicated Throne [Raid]: EQ2/encounter-coding/_Exp_21_Scars_of_Destruction/kael-drakkel-abdicated-throne-raid.md
        - Sodden Archipelago - Operation Cooperation [Raid]: EQ2/encounter-coding/_Exp_21_Scars_of_Destruction/sodden-archipelago-operation-cooperation-raid.md
        - Sodden Archipelago - Thawed Marshes [Raid]: EQ2/encounter-coding/_Exp_21_Scars_of_Destruction/sodden-archipelago-thawed-marshes-raid.md
        - Spiral of Vul [Contested]: EQ2/encounter-coding/_Exp_21_Scars_of_Destruction/spiral-of-vul-contested.md
        - Temple of Veeshan - Echoing Silence [Raid]: EQ2/encounter-coding/_Exp_21_Scars_of_Destruction/temple-of-veeshan-echoing-silence-raid.md
        - Western Wastes - Exploration Determination [Raid]: EQ2/encounter-coding/_Exp_21_Scars_of_Destruction/western-wastes-exploration-determination-raid.md
        - Western Wastes - Temple Crater [Raid]: EQ2/encounter-coding/_Exp_21_Scars_of_Destruction/western-wastes-temple-crater-raid.md
      - Ballads of Zimara:
        - Aether Wroughtlands - Ferric Fields [Heroic II]: EQ2/encounter-coding/_Exp_20_Ballads_of_Zimara/aether-wroughtlands-ferric-fields-heroic-ii.md
        - Aether Wroughtlands - Native Mettle [Heroic III]: EQ2/encounter-coding/_Exp_20_Ballads_of_Zimara/aether-wroughtlands-native-mettle-heroic-iii.md
        - Aether Wroughtlands - The Delves [Raid]: EQ2/encounter-coding/_Exp_20_Ballads_of_Zimara/aether-wroughtlands-the-delves-raid.md
        - Celebration Avatar Challenge - Bristlebane [Raid]: EQ2/encounter-coding/_Exp_20_Ballads_of_Zimara/celebration-avatar-challenge-bristlebane-raid.md
        - Celebration Avatar Challenge - Roehn Theer [Raid]: EQ2/encounter-coding/_Exp_20_Ballads_of_Zimara/celebration-avatar-challenge-roehn-theer-raid.md
        - Celebration Avatar Challenge - Tarew Marr [Raid]: EQ2/encounter-coding/_Exp_20_Ballads_of_Zimara/celebration-avatar-challenge-tarew-marr-raid.md
        - Celebration Avatar Challenge - Tunare [Raid]: EQ2/encounter-coding/_Exp_20_Ballads_of_Zimara/celebration-avatar-challenge-tunare-raid.md
        - Darkpaw Warrens [Heroic II]: EQ2/encounter-coding/_Exp_20_Ballads_of_Zimara/darkpaw-warrens-heroic-ii.md
        - Vaashkaani, Alcazar of Zimara - Chromatic Chamber [Raid]: EQ2/encounter-coding/_Exp_20_Ballads_of_Zimara/vaashkaani-alcazar-of-zimara-chromatic-chamber-raid.md
        - Vaashkaani, Alcazar of Zimara - Sovereign Summons [Raid]: EQ2/encounter-coding/_Exp_20_Ballads_of_Zimara/vaashkaani-alcazar-of-zimara-sovereign-summons-raid.md
        - Vaashkaani - Argent Sanctuary [Heroic II]: EQ2/encounter-coding/_Exp_20_Ballads_of_Zimara/vaashkaani-argent-sanctuary-heroic-ii.md
        - Vaashkaani, Royal Halls [Raid]: EQ2/encounter-coding/_Exp_20_Ballads_of_Zimara/vaashkaani-royal-halls-raid.md
        - Zimara Breadth - Crested Expanse [Raid]: EQ2/encounter-coding/_Exp_20_Ballads_of_Zimara/zimara-breadth-crested-expanse-raid.md
        - Zimara Breadth - Razing the Razelands [Heroic II]: EQ2/encounter-coding/_Exp_20_Ballads_of_Zimara/zimara-breadth-razing-the-razelands-heroic-ii.md
        - Zimara Breadth - Strungstone Ascent [Heroic II]: EQ2/encounter-coding/_Exp_20_Ballads_of_Zimara/zimara-breadth-strungstone-ascent-heroic-ii.md
      - Renewal of Ro:
        - Buried Takish'Hiz - Emergence from Stone [Raid]: EQ2/encounter-coding/_Exp_19_Renewal_of_Ro/buried-takish-hiz-emergence-from-stone-raid.md
        - Buried Takish'Hiz - Empire of Antiquity [Contested]: EQ2/encounter-coding/_Exp_19_Renewal_of_Ro/buried-takish-hiz-empire-of-antiquity-contested.md
        - Raj'Dur Plateaus - The Hunt [Raid]: EQ2/encounter-coding/_Exp_19_Renewal_of_Ro/raj-dur-plateaus-the-hunt-raid.md
        - Sandstone Delta - Grave Grange [Event Heroic II]: EQ2/encounter-coding/_Exp_19_Renewal_of_Ro/sandstone-delta-grave-grange-event-heroic-ii.md
        - Sandstone Delta - The Standing Storm [Raid]: EQ2/encounter-coding/_Exp_19_Renewal_of_Ro/sandstone-delta-the-standing-storm-raid.md
        - Shattered Unrest [Heroic III]: EQ2/encounter-coding/_Exp_19_Renewal_of_Ro/shattered-unrest-heroic-iii.md
        - Sultan's Mahallah - Daggers Drawn [Raid]: EQ2/encounter-coding/_Exp_19_Renewal_of_Ro/sultans-mahallah-daggers-drawn-raid.md
        - Takish Badlands - The Boundless Gulf [Raid]: EQ2/encounter-coding/_Exp_19_Renewal_of_Ro/takish-badlands-the-boundless-gulf-raid.md
        - Triad of Elements [Solo]: EQ2/encounter-coding/_Exp_19_Renewal_of_Ro/triad-of-elements-solo.md
      - Visions of Vetrovia:
        - Castle Vacrul - Caverns of the Forsaken [Heroic II]: EQ2/encounter-coding/_Exp_18_Visions_of_Vetrovia/castle-vacrul-caverns-of-the-forsaken-heroic-ii.md
        - Castle Vacrul - Haunting Presence [Raid]: EQ2/encounter-coding/_Exp_18_Visions_of_Vetrovia/castle-vacrul-haunting-presence-raid.md
        - Castle Vacrul - Thirst for Power [Raid]: EQ2/encounter-coding/_Exp_18_Visions_of_Vetrovia/castle-vacrul-thirst-for-power-raid.md
        - Forlorn Gist - Akashic Incursion [Raid]: EQ2/encounter-coding/_Exp_18_Visions_of_Vetrovia/forlorn-gist-akashic-incursion-raid.md
        - Forlorn Gist - Emerging Deceit [Raid]: EQ2/encounter-coding/_Exp_18_Visions_of_Vetrovia/forlorn-gist-emerging-deceit-raid.md
        - Karuupa Jungle - The Fading Light [Raid]: EQ2/encounter-coding/_Exp_18_Visions_of_Vetrovia/karuupa-jungle-the-fading-light-raid.md
        - Mahngavi Wastes - The Engulfing Night [Raid]: EQ2/encounter-coding/_Exp_18_Visions_of_Vetrovia/mahngavi-wastes-the-engulfing-night-raid.md
        - Svarni Expanse - Carrion Crag [Heroic]: EQ2/encounter-coding/_Exp_18_Visions_of_Vetrovia/svarni-expanse-carrion-crag-heroic.md
        - The Fabled Kurn's Tower [x2 Raid]: EQ2/encounter-coding/_Exp_18_Visions_of_Vetrovia/the-fabled-kurns-tower-x2-raid.md
        - The Fabled Kurn's Tower - Breaching the Void [Heroic]: EQ2/encounter-coding/_Exp_18_Visions_of_Vetrovia/the-fabled-kurns-tower-breaching-the-void-heroic.md
        - The Fabled Trakanon's Lair [Raid]: EQ2/encounter-coding/_Exp_18_Visions_of_Vetrovia/the-fabled-trakanons-lair-raid.md
        - The Fabled Veeshan's Peak [Raid]: EQ2/encounter-coding/_Exp_18_Visions_of_Vetrovia/the-fabled-veeshans-peak-raid.md
        - The Merchant's Den [Heroic II]: EQ2/encounter-coding/_Exp_18_Visions_of_Vetrovia/the-merchants-den-heroic-ii.md
      - Reign of Shadows:
        - Echo Caverns - Quarry Quandary [Heroic]: EQ2/encounter-coding/_Exp_17_Reign_of_Shadows/echo-caverns-quarry-quandary-heroic.md
        - Echo Caverns - Fungal Foray [Heroic]: EQ2/encounter-coding/_Exp_17_Reign_of_Shadows/echo-caverns-fungal-foray-heroic.md
        - Echo Caverns - Expedition Precarious [Raidventure]: EQ2/encounter-coding/_Exp_17_Reign_of_Shadows/echo-caverns-expedition-precarious-raidventure.md
        - Shadeweaver Thicket - Spirit Harvest [Raid]: EQ2/encounter-coding/_Exp_17_Reign_of_Shadows/shadeweaver-thicket-spirit-harvest-raid.md
        - Savage Weald - Shadow's Hold [Raid]: EQ2/encounter-coding/_Exp_17_Reign_of_Shadows/savage-weald-shadows-hold-raid.md
        - Savage Weald - Backwoods Brawl [Challenge]: EQ2/encounter-coding/_Exp_17_Reign_of_Shadows/savage-weald-backwoods-brawl-challenge.md
        - Vex Thal - Labyrinth of Solace [Raid]: EQ2/encounter-coding/_Exp_17_Reign_of_Shadows/vex-thal-labyrinth-of-solace-raid.md
        - Vex Thal - Edge of Oscuris [Challenge]: EQ2/encounter-coding/_Exp_17_Reign_of_Shadows/vex-thal-edge-of-oscuris-challenge.md
        - Vex Thal - Beyond the Veil [Raid]: EQ2/encounter-coding/_Exp_17_Reign_of_Shadows/vex-thal-beyond-the-veil-raid.md
        - Vasty Deep - Toil and Trouble [Heroic II]: EQ2/encounter-coding/_Exp_17_Reign_of_Shadows/vasty-deep-toil-and-trouble-heroic-ii.md
      - Blood of Luclin:
        - Aurelian Coast - The Emergent Eclipse [Raid]: EQ2/encounter-coding/_Exp_16_Blood_of_Luclin/aurelian-coast-the-emergent-eclipse-raid.md
        - Aurelian Coast - Maiden's Eye [Heroic]: EQ2/encounter-coding/_Exp_16_Blood_of_Luclin/aurelian-coast-maidens-eye-heroic.md
        - Fordel Midst - Remembrance [Raid]: EQ2/encounter-coding/_Exp_16_Blood_of_Luclin/fordel-midst-remembrance-raid.md
        - Fordel Midst - Bizarre Bazaar [Heroic]: EQ2/encounter-coding/_Exp_16_Blood_of_Luclin/fordel-midst-bizarre-bazaar-heroic.md
        - Sanctus Seru - Arx Aeturnus [Event Heroic]: EQ2/encounter-coding/_Exp_16_Blood_of_Luclin/sanctus-seru-arx-aeturnus-event-heroic.md
        - Sanctus Seru - Echelon of Divinity [Heroic]: EQ2/encounter-coding/_Exp_16_Blood_of_Luclin/sanctus-seru-echelon-of-divinity-heroic.md
        - Solusek's Eye - The Calling [Raid]: EQ2/encounter-coding/_Exp_16_Blood_of_Luclin/soluseks-eye-the-calling-raid.md
        - Ssraeshza's Hallowed Halls [Raid]: EQ2/encounter-coding/_Exp_16_Blood_of_Luclin/ssraeshzas-hallowed-halls-raid.md
        - The Blinding - Twisted Vista [Raid]: EQ2/encounter-coding/_Exp_16_Blood_of_Luclin/the-blinding-twisted-vista-raid.md
        - The Ruins of Ssraeshza [Heroic]: EQ2/encounter-coding/_Exp_16_Blood_of_Luclin/the-ruins-of-ssraeshza-heroic.md
        - The Venom of Ssraeshza [Event Heroic]: EQ2/encounter-coding/_Exp_16_Blood_of_Luclin/the-venom-of-ssraeshza-event-heroic.md
        - Wracklands - The Crimson Barrens [Raid]: EQ2/encounter-coding/_Exp_16_Blood_of_Luclin/wracklands-the-crimson-barrens-raid.md
        - Wracklands - Diaku Corral [Solo]: EQ2/encounter-coding/_Exp_16_Blood_of_Luclin/wracklands-diaku-corral-solo.md
    - Developer:
      - OgreBotAPI Reference: EQ2/developer/ogrebot-api.md
      - OgreCraftAPI Reference: EQ2/developer/ogrecraft-api.md
      - CampSpot System: EQ2/developer/camp-spot.md
      - Coding Practices: EQ2/developer/coding-practices.md
    - Community:
      - Contact: EQ2/community/contact.md
      - OgreIRC: EQ2/community/ogreirc.md
      - Feature Requests: EQ2/community/feature-requests.md
    - About:
      - Pricing: EQ2/about/pricing.md
      - Changelog: EQ2/about/changelog.md
